;============================================
; THIS FILE IS AUTOGENERATED BY KasTLe
; DO NOT MODIFY IT
;============================================

section .data

section .rodata
; Constant Strings
__string__0x7b26a2fe02d0:
    db "%x", 0x0A, "%x", 0x0A, 0x00
__string__0x7b26a2fe02f0:
    db "%d", 0x0A, 0x00

section .text
extern printf
extern scanf
extern calloc
extern free
extern gfx_init
extern gfx_close
extern gfx_clear
extern gfx_pixel
extern gfx_rect
extern gfx_present
extern gfx_delay
extern gfx_poll_event
extern gfx_key_pressed
extern gfx_mouse_x
extern gfx_mouse_y
extern gfx_mouse_pressed
extern gfx_get_color
global _start
_start:
    push rbp
    mov  rbp, rsp
    sub  rsp, 72
    mov  rax, 64
    cdqe
    mov  qword [rbp-16], rax
    mov  rax, 64
    cdqe
    mov  qword [rbp-24], rax
    lea  rax, qword [rbp-16]
    mov  rax, qword [rax]
    push rax
    mov  rax, 2
    cdqe
    pop  rdi
    cqo
    idiv rdi
    mov  qword [rbp-32], rax
    mov  rax, 10
    push rax
    lea  rax, qword [rbp-24]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rbp-16]
    mov  rax, qword [rax]
    push rax
    pop  rdi
    pop  rsi
    pop  rdx
    xor  rax, rax
    call gfx_init WRT ..plt
    mov  rax, 0
    push rax
    mov  rax, 0
    push rax
    mov  rax, 0
    push rax
    pop  rdi
    pop  rsi
    pop  rdx
    xor  rax, rax
    call gfx_get_color WRT ..plt
    mov  dword [rbp-40], eax
    mov  rax, 255
    push rax
    mov  rax, 255
    push rax
    mov  rax, 255
    push rax
    pop  rdi
    pop  rsi
    pop  rdx
    xor  rax, rax
    call gfx_get_color WRT ..plt
    mov  dword [rbp-48], eax
    lea  rax, qword [rbp-48]
    mov  eax, dword [rax]
    push rax
    lea  rax, qword [rbp-40]
    mov  eax, dword [rax]
    push rax
    lea  rax, qword [rel __string__0x7b26a2fe02d0]
    push rax
    pop  rdi
    pop  rsi
    pop  rdx
    xor  rax, rax
    call printf WRT ..plt
    lea  rax, qword [rbp-32]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rel __string__0x7b26a2fe02f0]
    push rax
    pop  rdi
    pop  rsi
    xor  rax, rax
    call printf WRT ..plt
    mov  rax, 0
    cdqe
    mov  qword [rbp-56], rax
.L1:
    lea  rax, qword [rbp-56]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rbp-16]
    mov  rax, qword [rax]
    pop  rdi
    cmp  rdi, rax
    setl al
    movzx rax, al
    test rax, rax
    jz   .L0
    mov  rax, 0
    cdqe
    mov  qword [rbp-64], rax
.L3:
    lea  rax, qword [rbp-64]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rbp-24]
    mov  rax, qword [rax]
    pop  rdi
    cmp  rdi, rax
    setl al
    movzx rax, al
    test rax, rax
    jz   .L2
    lea  rax, qword [rbp-56]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rbp-32]
    mov  rax, qword [rax]
    pop  rdi
    sub  rdi, rax
    mov  rax, rdi
    push rax
    mov  rax, 1
    pop  rdi
    sub  rdi, rax
    mov  rax, rdi
    push rax
    lea  rax, qword [rbp-56]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rbp-32]
    mov  rax, qword [rax]
    pop  rdi
    sub  rdi, rax
    mov  rax, rdi
    push rax
    mov  rax, 1
    pop  rdi
    sub  rdi, rax
    mov  rax, rdi
    pop  rdi
    imul rax, rdi
    push rax
    lea  rax, qword [rbp-64]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rbp-32]
    mov  rax, qword [rax]
    pop  rdi
    sub  rdi, rax
    mov  rax, rdi
    push rax
    mov  rax, 1
    pop  rdi
    sub  rdi, rax
    mov  rax, rdi
    push rax
    lea  rax, qword [rbp-64]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rbp-32]
    mov  rax, qword [rax]
    pop  rdi
    sub  rdi, rax
    mov  rax, rdi
    push rax
    mov  rax, 1
    pop  rdi
    sub  rdi, rax
    mov  rax, rdi
    pop  rdi
    imul rax, rdi
    pop  rdi
    add  rax, rdi
    push rax
    lea  rax, qword [rbp-32]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rbp-32]
    mov  rax, qword [rax]
    pop  rdi
    imul rax, rdi
    pop  rdi
    cmp  rdi, rax
    setl al
    movzx rax, al
    test rax, rax
    jz   .L4
    lea  rax, qword [rbp-40]
    mov  eax, dword [rax]
    push rax
    lea  rax, qword [rbp-64]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rbp-56]
    mov  rax, qword [rax]
    push rax
    pop  rdi
    pop  rsi
    pop  rdx
    xor  rax, rax
    call gfx_pixel WRT ..plt
    jmp  .L5
.L4:
    lea  rax, qword [rbp-48]
    mov  eax, dword [rax]
    push rax
    lea  rax, qword [rbp-64]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rbp-56]
    mov  rax, qword [rax]
    push rax
    pop  rdi
    pop  rsi
    pop  rdx
    xor  rax, rax
    call gfx_pixel WRT ..plt
.L5:
    lea  rax, qword [rbp-64]
    push rax
    lea  rax, qword [rbp-64]
    mov  rax, qword [rax]
    push rax
    mov  rax, 1
    pop  rdi
    add  rax, rdi
    pop  rdi
    mov  qword [rdi], rax
    jmp  .L3
.L2:
    lea  rax, qword [rbp-56]
    push rax
    lea  rax, qword [rbp-56]
    mov  rax, qword [rax]
    push rax
    mov  rax, 1
    pop  rdi
    add  rax, rdi
    pop  rdi
    mov  qword [rdi], rax
    jmp  .L1
.L0:
    xor  rax, rax
    call gfx_present WRT ..plt
.L7:
    mov  rax, 1
    test rax, rax
    jz   .L6
    xor  rax, rax
    call gfx_poll_event WRT ..plt
    push rax
    mov  rax, 1
    pop  rdi
    cmp  rdi, rax
    sete al
    movzx rax, al
    test rax, rax
    jz   .L8
    jmp  .L6
    jmp  .L8
.L8:
.L8:
    jmp  .L7
.L6:
    xor  rax, rax
    call gfx_close WRT ..plt
    mov  rax, 60
    xor  rdi, rdi
    syscall
