;============================================
; THIS FILE IS AUTOGENERATED BY KasTLe
; DO NOT MODIFY IT
;============================================

section .data

section .rodata
; Constant Strings

section .text
extern printf
extern scanf
extern calloc
extern free
extern gfx_init
extern gfx_close
extern gfx_clear
extern gfx_pixel
extern gfx_rect
extern gfx_present
extern gfx_delay
extern gfx_poll_event
extern gfx_key_pressed
extern gfx_mouse_x
extern gfx_mouse_y
extern gfx_mouse_pressed
extern gfx_get_color
global _start
_start:
    push rbp
    mov  rbp, rsp
    sub  rsp, 104
    mov  rax, 64
    cdqe
    mov  qword [rbp-16], rax
    mov  rax, 64
    cdqe
    mov  qword [rbp-24], rax
    mov  rax, 10
    push rax
    lea  rax, qword [rbp-24]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rbp-16]
    mov  rax, qword [rax]
    push rax
    pop  rdi
    pop  rsi
    pop  rdx
    xor  rax, rax
    call gfx_init WRT ..plt
    mov  rax, 0
    push rax
    mov  rax, 0
    push rax
    mov  rax, 0
    push rax
    pop  rdi
    pop  rsi
    pop  rdx
    xor  rax, rax
    call gfx_get_color WRT ..plt
    mov  dword [rbp-32], eax
    mov  rax, 255
    push rax
    mov  rax, 127
    push rax
    mov  rax, 255
    push rax
    pop  rdi
    pop  rsi
    pop  rdx
    xor  rax, rax
    call gfx_get_color WRT ..plt
    mov  dword [rbp-40], eax
    mov  rax, 0
    cdqe
    mov  qword [rbp-48], rax
    mov  rax, 0
    cdqe
    mov  qword [rbp-56], rax
    mov  rax, 82
    mov  dword [rbp-64], eax
    mov  rax, 81
    mov  dword [rbp-72], eax
    mov  rax, 80
    mov  dword [rbp-80], eax
    mov  rax, 79
    mov  dword [rbp-88], eax
.L1:
    mov  rax, 1
    test rax, rax
    jz   .L0
    xor  rax, rax
    call gfx_poll_event WRT ..plt
    push rax
    mov  rax, 1
    pop  rdi
    cmp  rdi, rax
    sete al
    movzx rax, al
    test rax, rax
    jz   .L2
    jmp  .L0
    jmp  .L2
.L2:
.L2:
    lea  rax, qword [rbp-64]
    mov  eax, dword [rax]
    push rax
    pop  rdi
    xor  rax, rax
    call gfx_key_pressed WRT ..plt
    test rax, rax
    jz   .L3
    lea  rax, qword [rbp-56]
    push rax
    lea  rax, qword [rbp-56]
    mov  rax, qword [rax]
    push rax
    mov  rax, 1
    pop  rdi
    sub  rdi, rax
    mov  rax, rdi
    pop  rdi
    mov  qword [rdi], rax
    lea  rax, qword [rbp-56]
    push rax
    lea  rax, qword [rbp-56]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rbp-16]
    mov  rax, qword [rax]
    pop  rdi
    cqo
    push rax
    mov  rax, rdi
    pop  rdi
    idiv rdi
    mov  rax, rdx
    pop  rdi
    mov  qword [rdi], rax
    jmp  .L4
.L3:
    lea  rax, qword [rbp-72]
    mov  eax, dword [rax]
    push rax
    pop  rdi
    xor  rax, rax
    call gfx_key_pressed WRT ..plt
    test rax, rax
    jz   .L5
    lea  rax, qword [rbp-56]
    push rax
    lea  rax, qword [rbp-56]
    mov  rax, qword [rax]
    push rax
    mov  rax, 1
    pop  rdi
    add  rax, rdi
    pop  rdi
    mov  qword [rdi], rax
    lea  rax, qword [rbp-56]
    push rax
    lea  rax, qword [rbp-56]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rbp-16]
    mov  rax, qword [rax]
    pop  rdi
    cqo
    push rax
    mov  rax, rdi
    pop  rdi
    idiv rdi
    mov  rax, rdx
    pop  rdi
    mov  qword [rdi], rax
    jmp  .L4
.L5:
    lea  rax, qword [rbp-80]
    mov  eax, dword [rax]
    push rax
    pop  rdi
    xor  rax, rax
    call gfx_key_pressed WRT ..plt
    test rax, rax
    jz   .L6
    lea  rax, qword [rbp-48]
    push rax
    lea  rax, qword [rbp-48]
    mov  rax, qword [rax]
    push rax
    mov  rax, 1
    pop  rdi
    sub  rdi, rax
    mov  rax, rdi
    pop  rdi
    mov  qword [rdi], rax
    lea  rax, qword [rbp-48]
    push rax
    lea  rax, qword [rbp-48]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rbp-24]
    mov  rax, qword [rax]
    pop  rdi
    cqo
    push rax
    mov  rax, rdi
    pop  rdi
    idiv rdi
    mov  rax, rdx
    pop  rdi
    mov  qword [rdi], rax
    jmp  .L4
.L6:
    lea  rax, qword [rbp-88]
    mov  eax, dword [rax]
    push rax
    pop  rdi
    xor  rax, rax
    call gfx_key_pressed WRT ..plt
    test rax, rax
    jz   .L7
    lea  rax, qword [rbp-48]
    push rax
    lea  rax, qword [rbp-48]
    mov  rax, qword [rax]
    push rax
    mov  rax, 1
    pop  rdi
    add  rax, rdi
    pop  rdi
    mov  qword [rdi], rax
    lea  rax, qword [rbp-48]
    push rax
    lea  rax, qword [rbp-48]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rbp-24]
    mov  rax, qword [rax]
    pop  rdi
    cqo
    push rax
    mov  rax, rdi
    pop  rdi
    idiv rdi
    mov  rax, rdx
    pop  rdi
    mov  qword [rdi], rax
    jmp  .L4
.L7:
.L4:
    lea  rax, qword [rbp-32]
    mov  eax, dword [rax]
    push rax
    pop  rdi
    xor  rax, rax
    call gfx_clear WRT ..plt
    lea  rax, qword [rbp-40]
    mov  eax, dword [rax]
    push rax
    lea  rax, qword [rbp-56]
    mov  rax, qword [rax]
    push rax
    lea  rax, qword [rbp-48]
    mov  rax, qword [rax]
    push rax
    pop  rdi
    pop  rsi
    pop  rdx
    xor  rax, rax
    call gfx_pixel WRT ..plt
    xor  rax, rax
    call gfx_present WRT ..plt
    mov  rax, 10
    push rax
    pop  rdi
    xor  rax, rax
    call gfx_delay WRT ..plt
    jmp  .L1
    jmp  .L1
.L0:
    xor  rax, rax
    call gfx_close WRT ..plt
    mov  rax, 60
    xor  rdi, rdi
    syscall
