    { "print", "printf", _I32,     { _I8_ptr   }, 1, true  },
    { "scan",  "scanf",  _I32,     { _I8_ptr,  }, 1, true  },
    { "alloc", "calloc", _I64_ptr, { _I64,_I64 }, 2, false },
    { "free",  "free",   _VOID,    { _I64_ptr  }, 1, false },
    { "SDL_Init", "SDL_Init", _I64, { _I64 },     1, false },
    { "SDL_CreateWindow", "SDL_CreateWindow",
      _I64_ptr, { _I8_ptr, _I64, _I64, _I64, _I64, _I64 },
      6, false },
    { "SDL_CreateRenderer", "SDL_CreateRenderer",
      _I64_ptr, { _I64_ptr, _I32, _I64 }, 3, false },
    { "SDL_DestroyRenderer", "SDL_DestroyRenderer",
      _VOID, { _I64_ptr }, 1, false },
    { "SDL_DestroyWindow", "SDL_DestroyWindow",
      _VOID, { _I64_ptr }, 1, false },
    { "SDL_Quit", "SDL_Quit",
      _VOID, { }, 0, false },
    { "SDL_CreateTexture", "SDL_CreateTexture",
    _I64_ptr, { _I64_ptr, _I64, _I64, _I64, _I64 },
    5, false },
    { "SDL_UpdateTexture", "SDL_UpdateTexture",
    _I64, { _I64_ptr, _I64_ptr, _I64_ptr, _I64 },
    4, false },
    { "SDL_RenderClear", "SDL_RenderClear",
    _I64, { _I64_ptr }, 1, false },
    { "SDL_RenderCopy", "SDL_RenderCopy",
    _I64, { _I64_ptr, _I64_ptr, _I64_ptr, _I64_ptr },
    4, false },
    { "SDL_RenderPresent", "SDL_RenderPresent",
    _VOID, { _I64_ptr }, 1, false },
    { "SDL_PollEvent", "SDL_PollEvent",
    _I64, { _I64_ptr }, 1, false },
    { "SDL_Delay", "SDL_Delay",
    _VOID, { _I64 }, 1, false },
    { "SDL_SetRenderDrawColor", "SDL_SetRenderDrawColor",
    _I64, { _I64_ptr, _I64, _I64, _I64, _I64 },
    5, false },
    { "SDL_DestroyTexture", "SDL_DestroyTexture",
    _VOID, { _I64_ptr }, 1, false }
