    /* ---- libc ---- */
    { "print",  "printf", _I32,     { _I8_ptr     }, 1, true  },
    { "scan",   "scanf",  _I32,     { _I8_ptr     }, 1, true  },
    { "alloc",  "calloc", _I64_ptr, { _I64, _I64  }, 2, false },
    { "free",   "free",   _VOID,    { _I64_ptr    }, 1, false },

    /* ---- libgfx ---- */
    { "gfx_init",          "gfx_init",          _I32,  { _I32, _I32, _I32           }, 3, false },
    { "gfx_close",         "gfx_close",         _VOID, {                            }, 0, false },
    { "gfx_clear",         "gfx_clear",         _VOID, { _I32                       }, 1, false },
    { "gfx_pixel",         "gfx_pixel",         _VOID, { _I32, _I32, _I32           }, 3, false },
    { "gfx_rect",          "gfx_rect",          _VOID, { _I32, _I32, _I32, _I32, _I32 }, 5, false },
    { "gfx_present",       "gfx_present",       _VOID, {                            }, 0, false },
    { "gfx_delay",         "gfx_delay",         _VOID, { _I32                       }, 1, false },
    { "gfx_poll_event",    "gfx_poll_event",    _I32,  {                            }, 0, false },
    { "gfx_key_pressed",   "gfx_key_pressed",   _I32,  { _I32                       }, 1, false },
    { "gfx_mouse_x",       "gfx_mouse_x",       _I32,  {                            }, 0, false },
    { "gfx_mouse_y",       "gfx_mouse_y",       _I32,  {                            }, 0, false },
    { "gfx_mouse_pressed", "gfx_mouse_pressed", _I32,  {                            }, 0, false },
    { "gfx_get_color",     "gfx_get_color",     _I32,  { _I8,  _I8,  _I8            }, 3, false },
