#ifndef TOKEN_ENUM_H
#define TOKEN_ENUM_H


enum KTL_TokenKind {
    KTL_TOKEN_KEY,
    KTL_TOKEN_STRING,
    KTL_TOKEN_VALUE,
    KTL_TOKEN_STR_LITERAL,
    KTL_TOKEN_PUNCT,
};

enum KTL_KeyWord {
    KTL_KEY_IF,
    KTL_KEY_ELIF,
    KTL_KEY_ELSE,

    KTL_KEY_WHILE,
    KTL_KEY_FOR,
    KTL_KEY_BREAK,
    KTL_KEY_CONTINUE,

    KTL_KEY_RETURN,
    KTL_KEY_ASSIGN,

    KTL_KEY_IN,
    KTL_KEY_OUT,

    KTL_KEY_TYPEDEF,
    KTL_KEY_STRUCT,

    KTL_KEY_VAR_DECL,
    KTL_KEY_FUNC_DECL,

    /* Поддержка сравнений для более удобного изменения конфигов */
    KTL_KEY_AND,
    KTL_KEY_OR,

    KTL_KEY_EQ,
    KTL_KEY_NEQ,
    KTL_KEY_LT,
    KTL_KEY_GT,
    KTL_KEY_LE,
    KTL_KEY_GE,
};

enum KTL_Oper {
    KTL_OPER_ADD,
    KTL_OPER_SUB,
    KTL_OPER_MUL,
    KTL_OPER_DIV,

    KTL_OPER_COMP_BE,
    KTL_OPER_COMP_B,
    KTL_OPER_COMP_LE,
    KTL_OPER_COMP_L,
    KTL_OPER_COMP_E,
    KTL_OPER_COMP_NE,

    KTL_OPER_GET_PTR,
    KTL_OPER_UNGET_PTR,
    KTL_OPER_ASSIGN,
};

enum KTL_Punct {
    KTL_PUNCT_COMMA,
    KTL_PUNCT_DOT,
    KTL_PUNCT_SEMICOLON,

    KTL_PUNCT_LEFT_ROUND,
    KTL_PUNCT_RIGHT_ROUND,
    KTL_PUNCT_LEFT_FIGURE,
    KTL_PUNCT_RIGHT_FIGURE,
    KTL_PUNCT_LEFT_TRIG,
    KTL_PUNCT_RIGHT_TRIG,
    KTL_PUNCT_LEFT_SQUARE,
    KTL_PUNCT_RIGHT_SQUARE,

    KTL_PUNCT_PLUS,
    KTL_PUNCT_MINUS,
    KTL_PUNCT_MUL,
    KTL_PUNCT_DEL,
    KTL_PUNCT_AMP,
    KTL_PUNCT_EXCL,

    KTL_PUNCT_GRID,
    KTL_PUNCT_DOLLAR,
    KTL_PUNCT_NEXT_STR,
    KTL_PUNCT_PROCENT,
    KTL_PUNCT_ASSIGN,

    KTL_PUNCT_EQ,
    KTL_PUNCT_NEQ,
    KTL_PUNCT_LE,
    KTL_PUNCT_GE,

    KTL_PUNCT_ARROW,
};

constexpr KTL_Punct KTL_PUNCT_FIRST_WITH_TWO_SYM = KTL_PUNCT_EQ;

#endif /* TOKEN_ENUM_H */
