#ifndef TOKEN_ENUM_H
#define TOKEN_ENUM_H


enum KTL_TokenKind {
    KTL_TOKEN_KEY,
    KTL_TOKEN_STRING,
    KTL_TOKEN_VALUE,
    KTL_TOKEN_STR_LITERAL,
    KTL_TOKEN_PUNCT,
    KTL_TOKEN_CHAR,
    KTL_TOKEN_EOF,
};

enum KTL_KeyWord {
    KTL_KEY_MAIN,

    KTL_KEY_IF,
    KTL_KEY_ELIF,
    KTL_KEY_ELSE,

    KTL_KEY_WHILE,
    KTL_KEY_FOR,
    KTL_KEY_BREAK,
    KTL_KEY_CONTINUE,

    KTL_KEY_RETURN,
    KTL_KEY_IN,
    KTL_KEY_OUT,

    KTL_KEY_TYPEDEF,
    KTL_KEY_STRUCT,

    KTL_KEY_VAR_DECL,
    KTL_KEY_FUNC_DECL,

    KTL_KEY_EXIT,

    /* Support compares for more simple changing configs */
    KTL_KEY_AND,
    KTL_KEY_OR,

    KTL_KEY_EQ,
    KTL_KEY_NEQ,
    KTL_KEY_LT,
    KTL_KEY_GT,
    KTL_KEY_LE,
    KTL_KEY_GE,

    /* Type Modes */
    KTL_KEY_CONST,
    KTL_KEY_MUTABLE,
    KTL_KEY_REGISTER,
    KTL_KEY_STACK,
};

enum KTL_Punct {
    /* One Symbols */
    KTL_PUNCT_COMMA,
    KTL_PUNCT_DOT,
    KTL_PUNCT_SEMICOLON,

    KTL_PUNCT_LEFT_ROUND,
    KTL_PUNCT_RIGHT_ROUND,
    KTL_PUNCT_LEFT_FIGURE,
    KTL_PUNCT_RIGHT_FIGURE,
    KTL_PUNCT_LEFT_TRIG,
    KTL_PUNCT_RIGHT_TRIG,
    KTL_PUNCT_LEFT_SQUARE,
    KTL_PUNCT_RIGHT_SQUARE,

    KTL_PUNCT_PLUS,
    KTL_PUNCT_MINUS,
    KTL_PUNCT_MUL,
    KTL_PUNCT_DEL,
    KTL_PUNCT_AMP,
    KTL_PUNCT_EXCL,

    KTL_PUNCT_GRID,
    KTL_PUNCT_DOLLAR,
    KTL_PUNCT_NEXT_STR,
    KTL_PUNCT_PROCENT,
    KTL_PUNCT_ASSIGN,
    KTL_PUNCT_QUOT,

    /* Two Symbols */
    KTL_PUNCT_EQ,
    KTL_PUNCT_NEQ,
    KTL_PUNCT_LE,
    KTL_PUNCT_GE,

    KTL_PUNCT_ARROW,
};

constexpr KTL_Punct KTL_PUNCT_FIRST_WITH_TWO_SYM = KTL_PUNCT_EQ;

#endif /* TOKEN_ENUM_H */
